# version: '3.8'

services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel-app
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www
      - ./backend/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: recruitment
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql
    # ports:
    #   - "3307:3306"
    networks:
      - laravel

  recruitment-frontend:
      build:
        context: ./frontend        # thư mục chứa React app và Dockerfile frontend
        dockerfile: Dockerfile
      container_name: recruitment-frontend
      ports:
        - "3001:80"                # map port 3000 host đến port 80 container (nginx serve React)
      networks:
        - laravel
volumes:
  dbdata:

networks:
  laravel:
