services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "8003:80"
    depends_on:
      - backend-web
    networks:
      - recruitment

  backend-app:
    build:
      context: ./backend
      target: backend-app
    container_name: backend-app
    restart: always
    expose:
      - "9000"
    depends_on:
      - postgres
    networks:
      - recruitment
    # environment:
    #   APP_ENV: production
    #   APP_DEBUG: 'false'
    #   APP_URL: http://backend-web
    #   DB_CONNECTION: pgsql
    #   DB_HOST: postgres
    #   DB_PORT: 5432
    #   DB_DATABASE: recruitment
    #   DB_USERNAME: postgres
    #   DB_PASSWORD: secret

  backend-web:
    build:
      context: ./backend
      target: backend-web
    container_name: backend-nginx
    restart: always
    depends_on:
      - backend-app
    ports:
      - "8000:80"
    networks:
      - recruitment

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: recruitment
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - recruitment

networks:
  recruitment:

volumes:
  pgdata:
