
services:
  nginx:
    build:
      context: ./frontend
    container_name: nginx
    restart: always
    ports:
      - "8003:80"
    depends_on:
      - backend
    networks:
      - recruitment

  backend:
    build:
      context: ./backend
    container_name: backend
    restart: always
    # environment:
    #   APP_ENV: production
    #   APP_KEY: base64:Y+YIy0qyCz8CNJ81Y/HaiweoVcBkqHaa/9bE3+WZTIs=
    #   APP_DEBUG: false
    #   APP_URL: http://localhost
    #   DB_HOST: mysql
    #   DB_DATABASE: recruitment
    #   DB_USERNAME: root
    #   DB_PASSWORD: secret
    networks:
      - recruitment

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: recruitment
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - recruitment

networks:
  recruitment:

volumes:
  dbdata:
