INSERT INTO recruitment.skills (candidate_id,resume_id,name,proficiency,description) VALUES
	 (101,NULL,'Lập trình',4,'Java, PHP, HTML, CSS, JavaScript, jQuery, Bootstrap'),
	 (101,NULL,'Cơ sở dữ liệu',4,'MySQL, PostGreSQL'),
	 (102,NULL,'Lập trình',4,'Java, PHP, HTML, CSS, JavaScript, jQuery, Bootstrap'),
	 (102,NULL,'Cơ sở dữ liệu',4,'MySQL, PostGreSQL'),
	 (103,NULL,'Lập trình',4,'Java, PHP, HTML, CSS, JavaScript, jQuery, Bootstrap'),
	 (103,NULL,'Cơ sở dữ liệu',4,'MySQL, PostGreSQL'),
	 (104,NULL,'Lập trình',4,'Java, PHP, Laravel, HTML, CSS, JavaScript, jQuery, ReactJS, Bootstrap'),
	 (104,NULL,'Cơ sở dữ liệu',4,'MySQL, PostGreSQL'),
	 (105,NULL,'Lập trình',4,'Java, PHP, Laravel, HTML, CSS, JavaScript, jQuery, ReactJS, Bootstrap'),
	 (105,NULL,'Cơ sở dữ liệu',4,'MySQL, PostGreSQL');
INSERT INTO recruitment.skills (candidate_id,resume_id,name,proficiency,description) VALUES
	 (106,NULL,'Lập trình',4,'Java, PHP, Laravel, HTML, CSS, JavaScript, jQuery, ReactJS, Bootstrap'),
	 (106,NULL,'Cơ sở dữ liệu',4,'MySQL, PostGreSQL'),
	 (107,NULL,'Lập trình',4,'Java, PHP, HTML, CSS, JavaScript, jQuery, ReactJS'),
	 (107,NULL,'Cơ sở dữ liệu',4,'PostGreSQL'),
	 (108,NULL,'Lập trình',4,'Java, PHP, HTML, CSS, JavaScript, jQuery, ReactJS'),
	 (108,NULL,'Cơ sở dữ liệu',4,'PostGreSQL'),
	 (109,NULL,'Lập trình',4,'Java, PHP, HTML, CSS, JavaScript, jQuery, ReactJS, Bootstrap'),
	 (109,NULL,'Cơ sở dữ liệu',4,'MySQL, PostGreSQL'),
	 (110,NULL,'Lập trình',4,'Java, PHP, HTML, CSS, JavaScript, jQuery, ReactJS, Bootstrap'),
	 (110,NULL,'Cơ sở dữ liệu',4,'MySQL, PostGreSQL');
INSERT INTO recruitment.skills (candidate_id,resume_id,name,proficiency,description) VALUES
	 (111,NULL,'Lập trình',4,'Java, PHP, HTML, CSS, JavaScript, jQuery, ReactJS, Bootstrap'),
	 (111,NULL,'Cơ sở dữ liệu',4,'MySQL, PostGreSQL'),
	 (112,NULL,'Lập trình',4,'PHP, Laravel, HTML, SCSS, JavaScript, jQuery, ReactJS, Tailwind'),
	 (112,NULL,'Cơ sở dữ liệu',4,'MySQL, PostGreSQL'),
	 (113,NULL,'Lập trình',4,'PHP, Laravel, HTML, SCSS, JavaScript, jQuery, ReactJS, Tailwind'),
	 (113,NULL,'Cơ sở dữ liệu',4,'MySQL, PostGreSQL'),
	 (114,NULL,'Lập trình',4,'PHP, Laravel, HTML, SCSS, JavaScript, jQuery, ReactJS, VueJS, Bootstrap, Tailwind'),
	 (114,NULL,'Cơ sở dữ liệu',4,'MySQL, PostGreSQL'),
	 (115,NULL,'Lập trình',4,'PHP, Laravel, HTML, SCSS, JavaScript, jQuery, ReactJS, VueJS, Bootstrap, Tailwind'),
	 (115,NULL,'Cơ sở dữ liệu',4,'MySQL, PostGreSQL');
INSERT INTO recruitment.skills (candidate_id,resume_id,name,proficiency,description) VALUES
	 (116,NULL,'Lập trình',4,'PHP, Laravel, HTML, SCSS, JavaScript, VueJS, Bootstrap'),
	 (116,NULL,'Cơ sở dữ liệu',4,'PostGreSQL'),
	 (117,NULL,'Lập trình',4,'PHP, Laravel, HTML, SCSS, JavaScript, VueJS, Bootstrap'),
	 (117,NULL,'Cơ sở dữ liệu',4,'MySQL, PostGreSQL'),
	 (118,NULL,'Lập trình',4,'PHP, Laravel, HTML, SCSS, JavaScript, jQuery, ReactJS, VueJS, Bootstrap, Tailwind'),
	 (118,NULL,'Cơ sở dữ liệu',4,'MySQL, PostGreSQL'),
	 (119,NULL,'Lập trình',4,'PHP, Laravel, HTML, SCSS, JavaScript, jQuery, ReactJS, VueJS, Bootstrap, Tailwind'),
	 (119,NULL,'Cơ sở dữ liệu',4,'MySQL, PostGreSQL'),
	 (120,NULL,'Kỹ năng chuyên môn',4,'- Giao tiếp, xử lý tình huống, quản lý thời gian'),
	 (120,NULL,'Kỹ năng khác',4,'Tiếng Anh, tiếng Nhật');
INSERT INTO recruitment.skills (candidate_id,resume_id,name,proficiency,description) VALUES
	 (121,NULL,'Kỹ năng chuyên môn',4,'- Giao tiếp, xử lý tình huống, quản lý thời gian'),
	 (121,NULL,'Kỹ năng khác',4,'Tiếng Anh, tiếng Nhật'),
	 (122,NULL,'Kỹ năng chuyên môn',4,'- Giao tiếp, xử lý tình huống, quản lý thời gian'),
	 (122,NULL,'Kỹ năng khác',4,'Tiếng Anh, tiếng Nhật'),
	 (123,NULL,'Kỹ năng chuyên môn',4,'- Giao tiếp, xử lý tình huống, quản lý thời gian'),
	 (123,NULL,'Kỹ năng khác',4,'Tiếng Anh, tiếng Nhật'),
	 (124,NULL,'Kỹ năng chuyên môn',4,'- Giao tiếp, xử lý tình huống, quản lý thời gian'),
	 (124,NULL,'Kỹ năng khác',4,'Tiếng Anh, tiếng Nhật'),
	 (125,NULL,'Kỹ năng chuyên môn',4,'- Giao tiếp, xử lý tình huống, quản lý thời gian'),
	 (125,NULL,'Kỹ năng khác',4,'Tiếng Anh, tiếng Nhật');
INSERT INTO recruitment.skills (candidate_id,resume_id,name,proficiency,description) VALUES
	 (126,NULL,'Kỹ năng chuyên môn',4,'- Giao tiếp, xử lý tình huống, quản lý thời gian'),
	 (126,NULL,'Kỹ năng khác',4,'Tiếng Anh, tiếng Nhật'),
	 (127,NULL,'Kỹ năng chuyên môn',4,'- Giao tiếp, xử lý tình huống, quản lý thời gian'),
	 (127,NULL,'Kỹ năng khác',4,'Tiếng Anh, tiếng Nhật'),
	 (128,NULL,'Lập trình',4,'Java, PHP, Laravel, HTML, CSS, JavaScript, jQuery, ReactJS, Bootstrap'),
	 (128,NULL,'Cơ sở dữ liệu',4,'MySQL, PostGreSQL'),
	 (129,NULL,'Lập trình',4,'Java, PHP, Laravel, HTML, CSS, JavaScript, jQuery, ReactJS, Bootstrap'),
	 (129,NULL,'Cơ sở dữ liệu',4,'MySQL, PostGreSQL'),
	 (130,NULL,'Lập trình',4,'Java, PHP, Laravel, HTML, CSS, JavaScript, jQuery, ReactJS, Bootstrap'),
	 (130,NULL,'Cơ sở dữ liệu',4,'MySQL, PostGreSQL');
INSERT INTO recruitment.skills (candidate_id,resume_id,name,proficiency,description) VALUES
	 (131,NULL,'Lập trình',4,'PHP, Laravel, HTML, SCSS, JavaScript, jQuery, ReactJS, Tailwind'),
	 (131,NULL,'Cơ sở dữ liệu',4,'MySQL, PostGreSQL'),
	 (132,NULL,'Kỹ năng chuyên môn',4,'- Giao tiếp, xử lý tình huống, quản lý thời gian'),
	 (132,NULL,'Kỹ năng khác',4,'Tiếng Anh, tiếng Nhật'),
	 (133,NULL,'Kỹ năng chuyên môn',4,'- Giao tiếp, xử lý tình huống, quản lý thời gian'),
	 (133,NULL,'Kỹ năng khác',4,'Tiếng Anh, tiếng Nhật'),
	 (134,NULL,'Lập trình',4,'Java, PHP, Laravel, HTML, CSS, JavaScript, jQuery, ReactJS, Bootstrap'),
	 (134,NULL,'Cơ sở dữ liệu',4,'MySQL, PostGreSQL'),
	 (101,1,'Lập trình',4,'Java, PHP, HTML, CSS, JavaScript, jQuery, Bootstrap'),
	 (101,1,'Cơ sở dữ liệu',4,'MySQL, PostGreSQL');
INSERT INTO recruitment.skills (candidate_id,resume_id,name,proficiency,description) VALUES
	 (102,2,'Lập trình',4,'Java, PHP, HTML, CSS, JavaScript, jQuery, Bootstrap'),
	 (102,2,'Cơ sở dữ liệu',4,'MySQL, PostGreSQL'),
	 (103,3,'Lập trình',4,'Java, PHP, HTML, CSS, JavaScript, jQuery, Bootstrap'),
	 (103,3,'Cơ sở dữ liệu',4,'MySQL, PostGreSQL'),
	 (104,4,'Lập trình',4,'Java, PHP, Laravel, HTML, CSS, JavaScript, jQuery, ReactJS, Bootstrap'),
	 (104,4,'Cơ sở dữ liệu',4,'MySQL, PostGreSQL'),
	 (105,5,'Lập trình',4,'Java, PHP, Laravel, HTML, CSS, JavaScript, jQuery, ReactJS, Bootstrap'),
	 (105,5,'Cơ sở dữ liệu',4,'MySQL, PostGreSQL'),
	 (106,6,'Lập trình',4,'Java, PHP, Laravel, HTML, CSS, JavaScript, jQuery, ReactJS, Bootstrap'),
	 (106,6,'Cơ sở dữ liệu',4,'MySQL, PostGreSQL');
INSERT INTO recruitment.skills (candidate_id,resume_id,name,proficiency,description) VALUES
	 (107,7,'Lập trình',4,'Java, PHP, HTML, CSS, JavaScript, jQuery, ReactJS'),
	 (107,7,'Cơ sở dữ liệu',4,'PostGreSQL'),
	 (108,8,'Lập trình',4,'Java, PHP, HTML, CSS, JavaScript, jQuery, ReactJS'),
	 (108,8,'Cơ sở dữ liệu',4,'PostGreSQL'),
	 (109,9,'Lập trình',4,'Java, PHP, HTML, CSS, JavaScript, jQuery, ReactJS, Bootstrap'),
	 (109,9,'Cơ sở dữ liệu',4,'MySQL, PostGreSQL'),
	 (110,10,'Lập trình',4,'Java, PHP, HTML, CSS, JavaScript, jQuery, ReactJS, Bootstrap'),
	 (110,10,'Cơ sở dữ liệu',4,'MySQL, PostGreSQL'),
	 (111,11,'Lập trình',4,'Java, PHP, HTML, CSS, JavaScript, jQuery, ReactJS, Bootstrap'),
	 (111,11,'Cơ sở dữ liệu',4,'MySQL, PostGreSQL');
INSERT INTO recruitment.skills (candidate_id,resume_id,name,proficiency,description) VALUES
	 (112,12,'Lập trình',4,'PHP, Laravel, HTML, SCSS, JavaScript, jQuery, ReactJS, Tailwind'),
	 (112,12,'Cơ sở dữ liệu',4,'MySQL, PostGreSQL'),
	 (113,13,'Lập trình',4,'PHP, Laravel, HTML, SCSS, JavaScript, jQuery, ReactJS, Tailwind'),
	 (113,13,'Cơ sở dữ liệu',4,'MySQL, PostGreSQL'),
	 (114,14,'Lập trình',4,'PHP, Laravel, HTML, SCSS, JavaScript, jQuery, ReactJS, VueJS, Bootstrap, Tailwind'),
	 (114,14,'Cơ sở dữ liệu',4,'MySQL, PostGreSQL'),
	 (115,15,'Lập trình',4,'PHP, Laravel, HTML, SCSS, JavaScript, jQuery, ReactJS, VueJS, Bootstrap, Tailwind'),
	 (115,15,'Cơ sở dữ liệu',4,'MySQL, PostGreSQL'),
	 (116,16,'Lập trình',4,'PHP, Laravel, HTML, SCSS, JavaScript, VueJS, Bootstrap'),
	 (116,16,'Cơ sở dữ liệu',4,'PostGreSQL');
INSERT INTO recruitment.skills (candidate_id,resume_id,name,proficiency,description) VALUES
	 (117,17,'Lập trình',4,'PHP, Laravel, HTML, SCSS, JavaScript, VueJS, Bootstrap'),
	 (117,17,'Cơ sở dữ liệu',4,'MySQL, PostGreSQL'),
	 (118,18,'Lập trình',4,'PHP, Laravel, HTML, SCSS, JavaScript, jQuery, ReactJS, VueJS, Bootstrap, Tailwind'),
	 (118,18,'Cơ sở dữ liệu',4,'MySQL, PostGreSQL'),
	 (119,19,'Lập trình',4,'PHP, Laravel, HTML, SCSS, JavaScript, jQuery, ReactJS, VueJS, Bootstrap, Tailwind'),
	 (119,19,'Cơ sở dữ liệu',4,'MySQL, PostGreSQL'),
	 (120,20,'Kỹ năng chuyên môn',4,'- Giao tiếp, xử lý tình huống, quản lý thời gian'),
	 (120,20,'Kỹ năng khác',4,'Tiếng Anh, tiếng Nhật'),
	 (121,21,'Kỹ năng chuyên môn',4,'- Giao tiếp, xử lý tình huống, quản lý thời gian'),
	 (121,21,'Kỹ năng khác',4,'Tiếng Anh, tiếng Nhật');
INSERT INTO recruitment.skills (candidate_id,resume_id,name,proficiency,description) VALUES
	 (122,22,'Kỹ năng chuyên môn',4,'- Giao tiếp, xử lý tình huống, quản lý thời gian'),
	 (122,22,'Kỹ năng khác',4,'Tiếng Anh, tiếng Nhật'),
	 (123,23,'Kỹ năng chuyên môn',4,'- Giao tiếp, xử lý tình huống, quản lý thời gian'),
	 (123,23,'Kỹ năng khác',4,'Tiếng Anh, tiếng Nhật'),
	 (124,24,'Kỹ năng chuyên môn',4,'- Giao tiếp, xử lý tình huống, quản lý thời gian'),
	 (124,24,'Kỹ năng khác',4,'Tiếng Anh, tiếng Nhật'),
	 (125,25,'Kỹ năng chuyên môn',4,'- Giao tiếp, xử lý tình huống, quản lý thời gian'),
	 (125,25,'Kỹ năng khác',4,'Tiếng Anh, tiếng Nhật'),
	 (126,26,'Kỹ năng chuyên môn',4,'- Giao tiếp, xử lý tình huống, quản lý thời gian'),
	 (126,26,'Kỹ năng khác',4,'Tiếng Anh, tiếng Nhật');
INSERT INTO recruitment.skills (candidate_id,resume_id,name,proficiency,description) VALUES
	 (127,27,'Kỹ năng chuyên môn',4,'- Giao tiếp, xử lý tình huống, quản lý thời gian'),
	 (127,27,'Kỹ năng khác',4,'Tiếng Anh, tiếng Nhật'),
	 (128,28,'Lập trình',4,'Java, PHP, Laravel, HTML, CSS, JavaScript, jQuery, ReactJS, Bootstrap'),
	 (128,28,'Cơ sở dữ liệu',4,'MySQL, PostGreSQL'),
	 (129,29,'Lập trình',4,'Java, PHP, Laravel, HTML, CSS, JavaScript, jQuery, ReactJS, Bootstrap'),
	 (129,29,'Cơ sở dữ liệu',4,'MySQL, PostGreSQL'),
	 (130,30,'Lập trình',4,'Java, PHP, Laravel, HTML, CSS, JavaScript, jQuery, ReactJS, Bootstrap'),
	 (130,30,'Cơ sở dữ liệu',4,'MySQL, PostGreSQL'),
	 (131,31,'Lập trình',4,'PHP, Laravel, HTML, SCSS, JavaScript, jQuery, ReactJS, Tailwind'),
	 (131,31,'Cơ sở dữ liệu',4,'MySQL, PostGreSQL');
INSERT INTO recruitment.skills (candidate_id,resume_id,name,proficiency,description) VALUES
	 (132,32,'Kỹ năng chuyên môn',4,'- Giao tiếp, xử lý tình huống, quản lý thời gian'),
	 (132,32,'Kỹ năng khác',4,'Tiếng Anh, tiếng Nhật'),
	 (133,33,'Kỹ năng chuyên môn',4,'- Giao tiếp, xử lý tình huống, quản lý thời gian'),
	 (133,33,'Kỹ năng khác',4,'Tiếng Anh, tiếng Nhật'),
	 (134,34,'Lập trình',4,'Java, PHP, Laravel, HTML, CSS, JavaScript, jQuery, ReactJS, Bootstrap'),
	 (134,34,'Cơ sở dữ liệu',4,'MySQL, PostGreSQL');
