<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CandidateSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('candidates')->insert([
            [
                'id' => 101,
                'user_id' => 101,
                'firstname' => 'Văn Phú',
                'lastname' => 'Trần',
                'gender' => 0,
                'dob' => '2001-01-08',
                'phone' => '0333333335',
                'email' => 'tranphudhak@gmail.com',
                'address' => 'Gia Lâm, Hà Nội',
                'location_id' => '1',
                'link' => 'https://github.com/',
                'objective' => 'Lập trình viên Web chuyên nghiệp',
                'desired_job' => 'Fullstack Web Developer',
                'desired_industry_id' => 1,
                'desired_jtype_id' => 3,
                'desired_jlevel_id' => 1,
                'desired_min_salary' => 3,
                'desired_max_salary' => 5,
                'job_yoe' => 1,
                'public_resume_id' => null
            ],
            [
                'id' => 102,
                'user_id' => 102,
                'firstname' => 'Mai Lan',
                'lastname' => 'Trần',
                'gender' => 1,
                'dob' => '2001-01-08',
                'phone' => '0333333335',
                'email' => 'tranphudhak@gmail.com',
                'address' => 'Gia Lâm, Hà Nội',
                'location_id' => '1',
                'link' => 'https://github.com/',
                'objective' => 'Lập trình viên Web chuyên nghiệp',
                'desired_job' => 'Fullstack Web Developer',
                'desired_industry_id' => 1,
                'desired_jtype_id' => 3,
                'desired_jlevel_id' => 1,
                'desired_min_salary' => 3,
                'desired_max_salary' => 5,
                'job_yoe' => 1,
                'public_resume_id' => null
            ],
            [
                'id' => 103,
                'user_id' => 103,
                'firstname' => 'Văn B',
                'lastname' => 'Trần',
                'gender' => 0,
                'dob' => '2001-01-08',
                'phone' => '0333333335',
                'email' => 'tranphudhak@gmail.com',
                'address' => 'Gia Lâm, Hà Nội',
                'location_id' => '1',
                'link' => 'https://github.com/',
                'objective' => 'Lập trình viên Web chuyên nghiệp',
                'desired_job' => 'Fullstack Web Developer',
                'desired_industry_id' => 1,
                'desired_jtype_id' => 3,
                'desired_jlevel_id' => 1,
                'desired_min_salary' => 3,
                'desired_max_salary' => 5,
                'job_yoe' => 0,
                'public_resume_id' => null
            ],
            [
                'id' => 104,
                'user_id' => 104,
                'firstname' => 'Mai Phương',
                'lastname' => 'Trần',
                'gender' => 1,
                'dob' => '1997-01-08',
                'phone' => '0333333335',
                'email' => 'tranphudhak@gmail.com',
                'address' => 'Gia Lâm, Hà Nội',
                'location_id' => '1',
                'link' => 'https://github.com/',
                'objective' => 'Lập trình viên Web chuyên nghiệp',
                'desired_job' => 'Fullstack Web Developer',
                'desired_industry_id' => 1,
                'desired_jtype_id' => 3,
                'desired_jlevel_id' => 1,
                'desired_min_salary' => 3,
                'desired_max_salary' => 5,
                'job_yoe' => 0,
                'public_resume_id' => null
            ],
            [
                'id' => 105,
                'user_id' => 105,
                'firstname' => 'Văn D',
                'lastname' => 'Trần',
                'gender' => 0,
                'dob' => '1998-01-08',
                'phone' => '0333333335',
                'email' => 'tranphudhak@gmail.com',
                'address' => 'Gia Lâm, Hà Nội',
                'location_id' => '1',
                'link' => 'https://github.com/',
                'objective' => 'Lập trình viên Web chuyên nghiệp',
                'desired_job' => 'Fullstack Web Developer',
                'desired_industry_id' => 1,
                'desired_jtype_id' => 3,
                'desired_jlevel_id' => 1,
                'desired_min_salary' => 3,
                'desired_max_salary' => 5,
                'job_yoe' => 1,
                'public_resume_id' => null
            ],
            [
                'id' => 106,
                'user_id' => 106,
                'firstname' => 'Văn E',
                'lastname' => 'Trần',
                'gender' => 0,
                'dob' => '2001-01-08',
                'phone' => '0333333335',
                'email' => 'tranphudhak@gmail.com',
                'address' => 'Gia Lâm, Hà Nội',
                'location_id' => '1',
                'link' => 'https://github.com/',
                'objective' => 'Lập trình viên Web chuyên nghiệp',
                'desired_job' => 'Fullstack Web Developer',
                'desired_industry_id' => 1,
                'desired_jtype_id' => 3,
                'desired_jlevel_id' => 1,
                'desired_min_salary' => 3,
                'desired_max_salary' => 5,
                'job_yoe' => 2,
                'public_resume_id' => null
            ],
            [
                'id' => 107,
                'user_id' => 107,
                'firstname' => 'Văn F',
                'lastname' => 'Trần',
                'gender' => 0,
                'dob' => '1997-01-08',
                'phone' => '0333333335',
                'email' => 'tranphudhak@gmail.com',
                'address' => 'Gia Lâm, Hà Nội',
                'location_id' => '1',
                'link' => 'https://github.com/',
                'objective' => 'Lập trình viên Web chuyên nghiệp',
                'desired_job' => 'Fullstack Web Developer',
                'desired_industry_id' => 1,
                'desired_jtype_id' => 3,
                'desired_jlevel_id' => 1,
                'desired_min_salary' => 3,
                'desired_max_salary' => 5,
                'job_yoe' => 1,
                'public_resume_id' => null
            ],
            [
                'id' => 108,
                'user_id' => 108,
                'firstname' => 'Văn G',
                'lastname' => 'Trần',
                'gender' => 0,
                'dob' => '2001-01-08',
                'phone' => '0333333335',
                'email' => 'tranphudhak@gmail.com',
                'address' => 'Gia Lâm, Hà Nội',
                'location_id' => '1',
                'link' => 'https://github.com/',
                'objective' => 'Lập trình viên Web chuyên nghiệp',
                'desired_job' => 'Fullstack Web Developer',
                'desired_industry_id' => 1,
                'desired_jtype_id' => 3,
                'desired_jlevel_id' => 1,
                'desired_min_salary' => 3,
                'desired_max_salary' => 5,
                'job_yoe' => 2,
                'public_resume_id' => null
            ],
            [
                'id' => 109,
                'user_id' => 109,
                'firstname' => 'Mai Hằng',
                'lastname' => 'Trần',
                'gender' => 1,
                'dob' => '2001-01-08',
                'phone' => '0333333335',
                'email' => 'tranphudhak@gmail.com',
                'address' => 'Gia Lâm, Hà Nội',
                'location_id' => '1',
                'link' => 'https://github.com/',
                'objective' => 'Lập trình viên Web chuyên nghiệp',
                'desired_job' => 'Fullstack Web Developer',
                'desired_industry_id' => 1,
                'desired_jtype_id' => 3,
                'desired_jlevel_id' => 1,
                'desired_min_salary' => 3,
                'desired_max_salary' => 5,
                'job_yoe' => 1,
                'public_resume_id' => null
            ],
            [
                'id' => 110,
                'user_id' => 110,
                'firstname' => 'Văn Nam',
                'lastname' => 'Trần',
                'gender' => 0,
                'dob' => '2001-01-08',
                'phone' => '0333333335',
                'email' => 'tranphudhak@gmail.com',
                'address' => 'Gia Lâm, Hà Nội',
                'location_id' => '1',
                'link' => 'https://github.com/',
                'objective' => 'Lập trình viên Web chuyên nghiệp',
                'desired_job' => 'Fullstack Web Developer',
                'desired_industry_id' => 1,
                'desired_jtype_id' => 3,
                'desired_jlevel_id' => 1,
                'desired_min_salary' => 3,
                'desired_max_salary' => 5,
                'job_yoe' => 2,
                'public_resume_id' => null
            ],
            [
                'id' => 111,
                'user_id' => 111,
                'firstname' => 'Văn Ba',
                'lastname' => 'Trần',
                'gender' => 0,
                'dob' => '2001-01-08',
                'phone' => '0333333335',
                'email' => 'tranphudhak@gmail.com',
                'address' => 'Gia Lâm, Hà Nội',
                'location_id' => '1',
                'link' => 'https://github.com/',
                'objective' => 'Lập trình viên Web chuyên nghiệp',
                'desired_job' => 'Fullstack Web Developer',
                'desired_industry_id' => 1,
                'desired_jtype_id' => 3,
                'desired_jlevel_id' => 1,
                'desired_min_salary' => 3,
                'desired_max_salary' => 5,
                'job_yoe' => 1,
                'public_resume_id' => null
            ],
            [
                'id' => 112,
                'user_id' => 112,
                'firstname' => 'Thị A',
                'lastname' => 'Nguyễn',
                'gender' => 1,
                'dob' => '2001-01-08',
                'phone' => '0333333335',
                'email' => 'tranphudhak@gmail.com',
                'address' => 'Gia Lâm, Hà Nội',
                'location_id' => '1',
                'link' => 'https://github.com/',
                'objective' => 'Lập trình viên Web chuyên nghiệp',
                'desired_job' => 'Fullstack Web Developer',
                'desired_industry_id' => 1,
                'desired_jtype_id' => 1,
                'desired_jlevel_id' => 2,
                'desired_min_salary' => 10,
                'desired_max_salary' => 15,
                'job_yoe' => 3,
                'public_resume_id' => null
            ],
            [
                'id' => 113,
                'user_id' => 113,
                'firstname' => 'Văn B',
                'lastname' => 'Nguyễn',
                'gender' => 0,
                'dob' => '2001-01-08',
                'phone' => '0333333335',
                'email' => 'tranphudhak@gmail.com',
                'address' => 'Gia Lâm, Hà Nội',
                'location_id' => '1',
                'link' => 'https://github.com/',
                'objective' => 'Lập trình viên Web chuyên nghiệp',
                'desired_job' => 'Fullstack Web Developer',
                'desired_industry_id' => 1,
                'desired_jtype_id' => 1,
                'desired_jlevel_id' => 2,
                'desired_min_salary' => 10,
                'desired_max_salary' => 15,
                'job_yoe' => 3,
                'public_resume_id' => null
            ],
            [
                'id' => 114,
                'user_id' => 114,
                'firstname' => 'Văn C',
                'lastname' => 'Nguyễn',
                'gender' => 0,
                'dob' => '2001-01-08',
                'phone' => '0333333335',
                'email' => 'tranphudhak@gmail.com',
                'address' => 'Gia Lâm, Hà Nội',
                'location_id' => '1',
                'link' => 'https://github.com/',
                'objective' => 'Lập trình viên Web chuyên nghiệp',
                'desired_job' => 'Fullstack Web Developer',
                'desired_industry_id' => 1,
                'desired_jtype_id' => 1,
                'desired_jlevel_id' => 2,
                'desired_min_salary' => 10,
                'desired_max_salary' => 15,
                'job_yoe' => 3,
                'public_resume_id' => null
            ],
            [
                'id' => 115,
                'user_id' => 115,
                'firstname' => 'Thị D',
                'lastname' => 'Nguyễn',
                'gender' => 1,
                'dob' => '2001-01-08',
                'phone' => '0333333335',
                'email' => 'tranphudhak@gmail.com',
                'address' => 'Gia Lâm, Hà Nội',
                'location_id' => '1',
                'link' => 'https://github.com/',
                'objective' => 'Lập trình viên Web chuyên nghiệp',
                'desired_job' => 'Fullstack Web Developer',
                'desired_industry_id' => 1,
                'desired_jtype_id' => 1,
                'desired_jlevel_id' => 2,
                'desired_min_salary' => 10,
                'desired_max_salary' => 15,
                'job_yoe' => 3,
                'public_resume_id' => null
            ],
            [
                'id' => 116,
                'user_id' => 116,
                'firstname' => 'Văn E',
                'lastname' => 'Nguyễn',
                'gender' => 0,
                'dob' => '2001-01-08',
                'phone' => '0333333335',
                'email' => 'tranphudhak@gmail.com',
                'address' => 'Gia Lâm, Hà Nội',
                'location_id' => '1',
                'link' => 'https://github.com/',
                'objective' => 'Lập trình viên Web chuyên nghiệp',
                'desired_job' => 'Fullstack Web Developer',
                'desired_industry_id' => 1,
                'desired_jtype_id' => 1,
                'desired_jlevel_id' => 2,
                'desired_min_salary' => 10,
                'desired_max_salary' => 15,
                'job_yoe' => 3,
                'public_resume_id' => null
            ],
            [
                'id' => 117,
                'user_id' => 117,
                'firstname' => 'Văn F',
                'lastname' => 'Nguyễn',
                'gender' => 0,
                'dob' => '2001-01-08',
                'phone' => '0333333335',
                'email' => 'tranphudhak@gmail.com',
                'address' => 'Gia Lâm, Hà Nội',
                'location_id' => '1',
                'link' => 'https://github.com/',
                'objective' => 'Lập trình viên Web chuyên nghiệp',
                'desired_job' => 'Fullstack Web Developer',
                'desired_industry_id' => 1,
                'desired_jtype_id' => 1,
                'desired_jlevel_id' => 2,
                'desired_min_salary' => 10,
                'desired_max_salary' => 15,
                'job_yoe' => 3,
                'public_resume_id' => null
            ],
            [
                'id' => 118,
                'user_id' => 118,
                'firstname' => 'Thị G',
                'lastname' => 'Nguyễn',
                'gender' => 1,
                'dob' => '2001-01-08',
                'phone' => '0333333335',
                'email' => 'tranphudhak@gmail.com',
                'address' => 'Gia Lâm, Hà Nội',
                'location_id' => '1',
                'link' => 'https://github.com/',
                'objective' => 'Lập trình viên Web chuyên nghiệp',
                'desired_job' => 'Fullstack Web Developer',
                'desired_industry_id' => 1,
                'desired_jtype_id' => 1,
                'desired_jlevel_id' => 2,
                'desired_min_salary' => 10,
                'desired_max_salary' => 15,
                'job_yoe' => 3,
                'public_resume_id' => null
            ],
            [
                'id' => 119,
                'user_id' => 119,
                'firstname' => 'Văn H',
                'lastname' => 'Nguyễn',
                'gender' => 0,
                'dob' => '2001-01-08',
                'phone' => '0333333335',
                'email' => 'tranphudhak@gmail.com',
                'address' => 'Gia Lâm, Hà Nội',
                'location_id' => '1',
                'link' => 'https://github.com/',
                'objective' => 'Lập trình viên Web chuyên nghiệp',
                'desired_job' => 'Fullstack Web Developer',
                'desired_industry_id' => 1,
                'desired_jtype_id' => 1,
                'desired_jlevel_id' => 2,
                'desired_min_salary' => 10,
                'desired_max_salary' => 15,
                'job_yoe' => 3,
                'public_resume_id' => null
            ],
            [
                'id' => 120,
                'user_id' => 120,
                'firstname' => 'Văn A',
                'lastname' => 'Phạm',
                'gender' => 0,
                'dob' => '2001-01-08',
                'phone' => '0333333335',
                'email' => 'tranphudhak@gmail.com',
                'address' => 'Gia Lâm, Hà Nội',
                'location_id' => '1',
                'link' => 'https://github.com/',
                'objective' => 'Chuyên viên tuyển dụng chuyên nghiệp',
                'desired_job' => 'Chuyên viên tuyển dụng',
                'desired_industry_id' => 5,
                'desired_jtype_id' => 1,
                'desired_jlevel_id' => 2,
                'desired_min_salary' => 6,
                'desired_max_salary' => 10,
                'job_yoe' => 1,
                'public_resume_id' => null
            ],
            [
                'id' => 121,
                'user_id' => 121,
                'firstname' => 'Thị B',
                'lastname' => 'Phạm',
                'gender' => 1,
                'dob' => '2001-01-08',
                'phone' => '0333333335',
                'email' => 'tranphudhak@gmail.com',
                'address' => 'Gia Lâm, Hà Nội',
                'location_id' => '1',
                'link' => 'https://github.com/',
                'objective' => 'Chuyên viên tuyển dụng chuyên nghiệp',
                'desired_job' => 'Chuyên viên tuyển dụng',
                'desired_industry_id' => 5,
                'desired_jtype_id' => 1,
                'desired_jlevel_id' => 2,
                'desired_min_salary' => 6,
                'desired_max_salary' => 10,
                'job_yoe' => 1,
                'public_resume_id' => null
            ],
            [
                'id' => 122,
                'user_id' => 122,
                'firstname' => 'Thị C',
                'lastname' => 'Phạm',
                'gender' => 1,
                'dob' => '2001-01-08',
                'phone' => '0333333335',
                'email' => 'tranphudhak@gmail.com',
                'address' => 'Gia Lâm, Hà Nội',
                'location_id' => '1',
                'link' => 'https://github.com/',
                'objective' => 'Chuyên viên tuyển dụng chuyên nghiệp',
                'desired_job' => 'Chuyên viên tuyển dụng',
                'desired_industry_id' => 5,
                'desired_jtype_id' => 1,
                'desired_jlevel_id' => 2,
                'desired_min_salary' => 6,
                'desired_max_salary' => 10,
                'job_yoe' => 1,
                'public_resume_id' => null
            ],
            [
                'id' => 123,
                'user_id' => 123,
                'firstname' => 'Thị D',
                'lastname' => 'Phạm',
                'gender' => 1,
                'dob' => '2001-01-08',
                'phone' => '0333333335',
                'email' => 'tranphudhak@gmail.com',
                'address' => 'Gia Lâm, Hà Nội',
                'location_id' => '1',
                'link' => 'https://github.com/',
                'objective' => 'Chuyên viên tuyển dụng chuyên nghiệp',
                'desired_job' => 'Chuyên viên tuyển dụng',
                'desired_industry_id' => 5,
                'desired_jtype_id' => 1,
                'desired_jlevel_id' => 2,
                'desired_min_salary' => 6,
                'desired_max_salary' => 10,
                'job_yoe' => 1,
                'public_resume_id' => null
            ],
            [
                'id' => 124,
                'user_id' => 124,
                'firstname' => 'Văn E',
                'lastname' => 'Phạm',
                'gender' => 0,
                'dob' => '2001-01-08',
                'phone' => '0333333335',
                'email' => 'tranphudhak@gmail.com',
                'address' => 'Gia Lâm, Hà Nội',
                'location_id' => '1',
                'link' => 'https://github.com/',
                'objective' => 'Chuyên viên tuyển dụng chuyên nghiệp',
                'desired_job' => 'Chuyên viên tuyển dụng',
                'desired_industry_id' => 5,
                'desired_jtype_id' => 1,
                'desired_jlevel_id' => 2,
                'desired_min_salary' => 6,
                'desired_max_salary' => 10,
                'job_yoe' => 1,
                'public_resume_id' => null
            ],
            [
                'id' => 125,
                'user_id' => 125,
                'firstname' => 'Văn F',
                'lastname' => 'Phạm',
                'gender' => 0,
                'dob' => '2001-01-08',
                'phone' => '0333333335',
                'email' => 'tranphudhak@gmail.com',
                'address' => 'Gia Lâm, Hà Nội',
                'location_id' => '1',
                'link' => 'https://github.com/',
                'objective' => 'Chuyên viên tuyển dụng chuyên nghiệp',
                'desired_job' => 'Chuyên viên tuyển dụng',
                'desired_industry_id' => 5,
                'desired_jtype_id' => 1,
                'desired_jlevel_id' => 2,
                'desired_min_salary' => 6,
                'desired_max_salary' => 10,
                'job_yoe' => 1,
                'public_resume_id' => null
            ],
            [
                'id' => 126,
                'user_id' => 126,
                'firstname' => 'Thị G',
                'lastname' => 'Phạm',
                'gender' => 1,
                'dob' => '2001-01-08',
                'phone' => '0333333335',
                'email' => 'tranphudhak@gmail.com',
                'address' => 'Gia Lâm, Hà Nội',
                'location_id' => '1',
                'link' => 'https://github.com/',
                'objective' => 'Chuyên viên tuyển dụng chuyên nghiệp',
                'desired_job' => 'Chuyên viên tuyển dụng',
                'desired_industry_id' => 5,
                'desired_jtype_id' => 1,
                'desired_jlevel_id' => 2,
                'desired_min_salary' => 6,
                'desired_max_salary' => 10,
                'job_yoe' => 1,
                'public_resume_id' => null
            ],
            [
                'id' => 127,
                'user_id' => 127,
                'firstname' => 'Thị H',
                'lastname' => 'Phạm',
                'gender' => 1,
                'dob' => '2001-01-08',
                'phone' => '0333333335',
                'email' => 'tranphudhak@gmail.com',
                'address' => 'Gia Lâm, Hà Nội',
                'location_id' => '1',
                'link' => 'https://github.com/',
                'objective' => 'Chuyên viên tuyển dụng chuyên nghiệp',
                'desired_job' => 'Chuyên viên tuyển dụng',
                'desired_industry_id' => 5,
                'desired_jtype_id' => 1,
                'desired_jlevel_id' => 2,
                'desired_min_salary' => 6,
                'desired_max_salary' => 10,
                'job_yoe' => 1,
                'public_resume_id' => null
            ],

            [
                'id' => 128,
                'user_id' => 128,
                'firstname' => 'Văn A',
                'lastname' => 'Ngô',
                'gender' => 0,
                'dob' => '2001-01-08',
                'phone' => '0333333335',
                'email' => 'tranphudhak@gmail.com',
                'address' => 'Gia Lâm, Hà Nội',
                'location_id' => '2',
                'link' => 'https://github.com/',
                'objective' => 'Lập trình viên Web chuyên nghiệp',
                'desired_job' => 'Fullstack Web Developer',
                'desired_industry_id' => 1,
                'desired_jtype_id' => 3,
                'desired_jlevel_id' => 1,
                'desired_min_salary' => 3,
                'desired_max_salary' => 5,
                'job_yoe' => 1,
                'public_resume_id' => null
            ],
            [
                'id' => 129,
                'user_id' => 129,
                'firstname' => 'Văn B',
                'lastname' => 'Ngô',
                'gender' => 0,
                'dob' => '2001-01-08',
                'phone' => '0333333335',
                'email' => 'tranphudhak@gmail.com',
                'address' => 'Gia Lâm, Hà Nội',
                'location_id' => '2',
                'link' => 'https://github.com/',
                'objective' => 'Lập trình viên Web chuyên nghiệp',
                'desired_job' => 'Fullstack Web Developer',
                'desired_industry_id' => 1,
                'desired_jtype_id' => 3,
                'desired_jlevel_id' => 1,
                'desired_min_salary' => 3,
                'desired_max_salary' => 5,
                'job_yoe' => 1,
                'public_resume_id' => null
            ],
            [
                'id' => 130,
                'user_id' => 130,
                'firstname' => 'Văn C',
                'lastname' => 'Ngô',
                'gender' => 0,
                'dob' => '2001-01-08',
                'phone' => '0333333335',
                'email' => 'tranphudhak@gmail.com',
                'address' => 'Gia Lâm, Hà Nội',
                'location_id' => '1',
                'link' => 'https://github.com/',
                'objective' => 'Lập trình viên Web chuyên nghiệp',
                'desired_job' => 'Fullstack Web Developer',
                'desired_industry_id' => 1,
                'desired_jtype_id' => 1,
                'desired_jlevel_id' => 2,
                'desired_min_salary' => 10,
                'desired_max_salary' => 15,
                'job_yoe' => 3,
                'public_resume_id' => null
            ],
            [
                'id' => 131,
                'user_id' => 131,
                'firstname' => 'Văn D',
                'lastname' => 'Ngô',
                'gender' => 0,
                'dob' => '2001-01-08',
                'phone' => '0333333335',
                'email' => 'tranphudhak@gmail.com',
                'address' => 'Gia Lâm, Hà Nội',
                'location_id' => '1',
                'link' => 'https://github.com/',
                'objective' => 'Lập trình viên Web chuyên nghiệp',
                'desired_job' => 'Fullstack Web Developer',
                'desired_industry_id' => 1,
                'desired_jtype_id' => 1,
                'desired_jlevel_id' => 2,
                'desired_min_salary' => 10,
                'desired_max_salary' => 15,
                'job_yoe' => 3,
                'public_resume_id' => null
            ],
            [
                'id' => 132,
                'user_id' => 132,
                'firstname' => 'Thị E',
                'lastname' => 'Ngô',
                'gender' => 1,
                'dob' => '2001-01-08',
                'phone' => '0333333335',
                'email' => 'tranphudhak@gmail.com',
                'address' => 'Gia Lâm, Hà Nội',
                'location_id' => '1',
                'link' => 'https://github.com/',
                'objective' => 'Chuyên viên tuyển dụng chuyên nghiệp',
                'desired_job' => 'Chuyên viên tuyển dụng',
                'desired_industry_id' => 5,
                'desired_jtype_id' => 1,
                'desired_jlevel_id' => 2,
                'desired_min_salary' => 6,
                'desired_max_salary' => 10,
                'job_yoe' => 1,
                'public_resume_id' => null
            ],
            [
                'id' => 133,
                'user_id' => 133,
                'firstname' => 'Thị F',
                'lastname' => 'Ngô',
                'gender' => 1,
                'dob' => '2001-01-08',
                'phone' => '0333333335',
                'email' => 'tranphudhak@gmail.com',
                'address' => 'Gia Lâm, Hà Nội',
                'location_id' => '1',
                'link' => 'https://github.com/',
                'objective' => 'Chuyên viên tuyển dụng chuyên nghiệp',
                'desired_job' => 'Chuyên viên tuyển dụng',
                'desired_industry_id' => 5,
                'desired_jtype_id' => 1,
                'desired_jlevel_id' => 2,
                'desired_min_salary' => 6,
                'desired_max_salary' => 10,
                'job_yoe' => 1,
                'public_resume_id' => null
            ],
        ]);
    }
}
